# we not track data because that size is around 8GB while other project track , because
# dvc just not track data the also make cache file of data. so if we set S3 remote then
# need to push 8GB data and data trafic also a problem : storage + networking
# Note: we can track but at this time not do it

stages:
  data_ingestion: 
    cmd: python ./src/data/data_ingestion.py
    deps:
      - ./src/data/data_ingestion.py

  extract_features:
    cmd: python ./src/features/extract_features.py
    deps: 
      - ./src/features/extract_features.py
    params: 
      - extract_features.mini_batch_kmeans.n_clusters
      - extract_features.mini_batch_kmeans.n_init
      - extract_features.mini_batch_kmeans.random_state
      - extract_features.ewma.alpha
    outs:
      - ./data/processed/resampled_data.csv
      - ./models/scaler.joblib
      - ./models/mb_kmeans.joblib

  feature_processing:
    cmd: python ./src/features/feature_processing.py
    deps:
      - ./src/features/feature_processing.py
      - ./data/processed/resampled_data.csv
    outs:
      - ./data/processed/train.csv
      - ./data/processed/test.csv

  